### ISSUE TITLE
Missing File: train_SAM_point_top3_mask_boundary_P2B_he_mask_he1.json

### ISSUE THREAD

**Issue by HIM** [zhaoyangwei123/SAPNet#1]
Hello,

Thank you for your amazing work! I encountered an issue while running the code. The error message indicates that the file 'data/coco/annotations/train_SAM_point_top3_mask_boundary_P2B_he_mask_he1.json' is missing. However, this file is not provided in the repository.

Could you please provide this file or guide me on how to generate it? Any help would be greatly appreciated.

Thank you for your assistance!

Best regards.

**Comment by zhaoyangwei123** [comment]
In the TOV_mmdetection of this project, you can find the Google drive for annotation files and the generation method for point annotations

**Comment by HIM** [comment]
我申请了这个谷歌网盘的访问权限https://drive.google.com/drive/folders/1TKy9DpvNAqr5IdMG85NjDFp_X7iUryk-?usp=drive_link，可以通过一下吗😊

**Comment by zhaoyangwei123** [comment]
> Quote reply

ok啦

**Comment by zhaoyangwei123** [comment]
> 我申请了这个谷歌网盘的访问权限[https://drive.google.com/drive/folders/1TKy9DpvNAqr5IdMG85NjDFp_X7iUryk-?usp=drive_link，可以通过一下吗😊](https://drive.google.com/drive/folders/1TKy9DpvNAqr5IdMG85NjDFp_X7iUryk-?usp=drive_link%EF%BC%8C%E5%8F%AF%E4%BB%A5%E9%80%9A%E8%BF%87%E4%B8%80%E4%B8%8B%E5%90%97%F0%9F%98%8A)

ok啦

**Comment by HIM** [comment]
谢谢！请问您可以公布一下VOC2012的数据集准备代码以及训练和测试代码吗

**Comment by zhaoyangwei123** [comment]
> 谢谢！请问您可以公布一下VOC2012的数据集准备代码以及训练和测试代码吗

voc的config在coco上面改一下数据集和学习率就行，相关标注json文件稍后会上传Google云盘

**Comment by zhangyuguiUCAS** [comment]
sam_results_with_point_prompt_coco.json这个文件是如何从coco_train2017.json生成的呢？

**Comment by zhaoyangwei123** [comment]
> sam_results_with_point_prompt_coco.json这个文件是如何从coco_train2017.json生成的呢？

这个是将点标签给SAM得出来的，你可以在https://drive.google.com/drive/folders/1TKy9DpvNAqr5IdMG85NjDFp_X7iUryk-找到，相应的标注我已经开放权限了

**Comment by zhangyuguiUCAS** [comment]
感谢您的回复，我想做的是把我的数据集转换成coco格式，再将annotation转换为sam_results_with_point_prompt_coco.json的格式，我是应该按照教程生成qc_instance_train2017_coarse_with_gt.json格式的文件，再将其用SAM处理得到所需文件吗？

**Comment by zhaoyangwei123** [comment]
> 感谢您的回复，我想做的是把我的数据集转换成coco格式，再将annotation转换为sam_results_with_point_prompt_coco.json的格式，我是应该按照教程生成qc_instance_train2017_coarse_with_gt.json格式的文件，再将其用SAM处理得到所需文件吗？

是的，对于自定义的数据集的话建议转成coco格式再考虑利用所提供的工具生成point，然后再利用SAM进行处理
