### ISSUE TITLE
What py file is the loss function for the "Proposals Refinement Module"?

### ISSUE THREAD

**Issue by LYF-bnu** [zhaoyangwei123/SAPNet#3]
What py file is the loss function for the "Proposals Refinement Module"?  I can not
 find it.

**Comment by zhaoyangwei123** [comment]
The loss function in the Proposals Refinement Module stage does not have a fixed py file, and it overlaps with the loss in the PSM stage to some extent. It adds negative case losses and changes the positive case loss function. Although the loss function in the article is written in the Proposals Refinement Module section, it is the total loss function of the model. If you want to understand the specific process of loss propagation, I suggest understanding the mmdetection mechanism and debugging it first

**Comment by LYF-bnu** [comment]
Thank you!
